In [1]:
import numpy as np

In [2]:
a=[1,2,3]
b=[4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [7]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1+arr2)
print(arr1.ndim)
print(arr1.size)
print(arr1.shape)
print(arr1*arr2)
print(arr1-arr2)
print(arr1/arr2)


[5 7 9]
1
3
(3,)
[ 4 10 18]
[-3 -3 -3]
[0.25 0.4  0.5 ]


In [8]:
a=[1,2,3]
3*a

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [9]:
arr1=np.array([1,2,3])
3*arr1

array([3, 6, 9])

In [13]:
b=np.array([1,2,3])
print(b)
print(np.repeat(b,3))
print(np.tile(b,3))

[1 2 3]
[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [20]:
c=np.arange(9)
c=c.reshape(3,3)
print(c.shape)
print(c)
print(np.repeat(c,3))
np.tile(c,3)

(3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6 7 7 7 8 8 8]


array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8, 6, 7, 8]])

In [23]:
arr2=np.array([4,5,6])
print(arr2**2)
#  take arr1 from previous code snips
print(arr1/(arr2**2))

[16 25 36]
[0.0625     0.08       0.08333333]


In [24]:
arr3=np.array([10,20,30,40])
print(arr3)
print(arr3>10)

[10 20 30 40]
[False  True  True  True]


In [26]:
help(np.ufunc)   
#universal funtions

Help on class ufunc in module numpy:

class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |
 |  **Calling ufuncs:** ``op(*x[, out], where=True, **kwargs)``
 |
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |
 |  The broadcasting rules are:
 |
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, ..., or tuple of ndarray and None, optional
 |      Location(s) into which the result

In [28]:
x=np.array([0,1,2,3])
print(x**3)
#sqrt of original x . x^3 is not assigned so it remains original
print(np.sqrt(x))

[ 0  1  8 27]
[0.         1.         1.41421356 1.73205081]


In [34]:
x=np.arange(1,11)
print(x)
print(x.sum())
print(x.cumsum())
print(x.mean())
print(x.std())
print(x.var())
print(x.max())
print(x.min())
#find loc of max and min
print(x.argmax())
print(x.argmin())

[ 1  2  3  4  5  6  7  8  9 10]
55
[ 1  3  6 10 15 21 28 36 45 55]
5.5
2.8722813232690143
8.25
10
1
9
0


In [42]:
x=np.arange(1,11)
x_mean=x.mean()
print(x_mean)
dev=x-x_mean
print(dev)
sqdev=dev**2
print(sqdev)
sumsqdev=sqdev.sum()
print(sumsqdev)
var=sumsqdev/x.size
print(var)
print(x.var())
sd=np.sqrt(var)
print(sd)
print(x.std())


5.5
[-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
[20.25 12.25  6.25  2.25  0.25  0.25  2.25  6.25 12.25 20.25]
82.5
8.25
8.25
2.8722813232690143
2.8722813232690143


In [46]:
x=np.arange(1,7)
print(x)
print(x.reshape(2,3))
print(x.reshape(2,-1))
print(x.reshape(3,-1))
x=x.reshape(2,3)
print(x.mean(axis=0))
print(x.mean(axis=1))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[2.5 3.5 4.5]
[2. 5.]


In [64]:
import numpy as np

np.random.seed(123)   # set seed

print(np.random.rand(3))

[0.69646919 0.28613933 0.22685145]


In [50]:
print(np.random.randint(10))
print(np.random.randint(1,11))

2
7


In [51]:
while(True):
    num=np.random.randint(1,11)
    print(num)
    if(num==10):
        break

2
4
10


In [66]:
x=np.array([0,1,2,3,4,5])
print(np.sqrt(x))
print(np.exp(x))

[0.         1.         1.41421356 1.73205081 2.         2.23606798]
[  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591 ]


In [84]:
np.random.seed(123)
a=np.random.randint(1,11,size=1000)
print(a)
print(a.size)
print(np.unique(a))
print(np.median(a))
print(np.sum(a))
print(np.round(np.var(a),2))
print(np.round(np.mean(a),2))
print(np.round(np.std(a),2))
print(np.max(a))
print(np.min(a))
#first occurance of max and min
print(np.argmax(a))
print(np.argmin(a))


[ 3  3  7  2  4 10  7  2  1  2 10  1  1 10  4  5  1  1  5  2  8  4  3  5
  8  3  5  9  1  8 10  4  5  7  2  6  7  3  2  9  4  6  1  3  7  3  5  5
  7  4  1  7  5  8  7  8  2  6  8 10  3  5  9  2  3  2  2  4  6 10  1  9
  2  7  4  4  6 10  8 10  3  4  4  4  9  7 10  8  7  4 10  7  7  7  2  4
  5  4  2  1  6  9  7  9 10  2  1  4  2  4  5  8  7  2  5  4  4  8  7  9
  7  5  5  8  1  1 10  9  9  5  9  7  2  7  9  8 10  2  8  2  8 10  9  8
  2  4  2  9  8  6  2  3  6  3  3 10  4  3  7  8 10  2  4  9  4  8 10 10
  4  4  6  7  1  9  8  8  5  5  6  1  9 10  3  6  2  6 10  3  5  4  1  4
  8  8  3  6  2  8  6 10  2  3  9  6  1 10  4  4  4  2  8  7  4  2  8  3
  7  6 10  9 10  5  8  9  6 10  3  5  4  4  2  8  9  6  8  8  8  6  1  1
  9  2  1  5  6  5  6  1  8  2  3  3  8  8  4  7  2  9  5  2  7  6 10  1
  4  2  4  8  8  8  6  4  7  4  6  2  6 10  2  4 10  2  6  7  2  6  1  8
  1  4  1  7  3  8  6  2  1  1  3  7  6 10  2  6  4  7  5  8  2  7  1  4
  2  4  1  9  6  2  5  4  3  3  1  3  1  3  8 10  1

In [91]:
a=np.array([0,1,2,3]).reshape(2,2)
b=np.array([3,2,0,1]).reshape(2,2)
print(a)
print(b)
print(a.dot(b))
print(np.dot(a,b))
print(np.transpose(a))
print(np.linalg.inv(a))
print(np.linalg.det(a))

[[0 1]
 [2 3]]
[[3 2]
 [0 1]]
[[0 1]
 [6 7]]
[[0 1]
 [6 7]]
[[0 2]
 [1 3]]
[[-1.5  0.5]
 [ 1.   0. ]]
-2.0
