In [32]:
import numpy as np

a= np.array([0,1,2,3])
b= np.array([[0,1,2,3],
             [4,5,6,7],
             [8,9,10,11]])

print(a[0])

print(b[0])

print(b[1][2])

print(b[1,2])

a1 = np.array([0,10,20,30,40,50])
print(a1)
a1[3]= 35
print(a1)

print(a1[[1,3,4]])   #1, 3, 4 are index values 

a2 = np.arange(10,100,10).reshape(3,3)
print(a2)

print(a2[0,2])

a2[2,2] = 95
print(a2)

print(a2[1])

a2[2] = np.array([45,55,65])
print(a2)

print(a2[[0,2],[0,1]])    #[0,2] >> row numbers of two numbers [0,1]>> column numbers



0
[0 1 2 3]
6
6
[ 0 10 20 30 40 50]
[ 0 10 20 35 40 50]
[10 35 40]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
30
[[10 20 30]
 [40 50 60]
 [70 80 95]]
[40 50 60]
[[10 20 30]
 [40 50 60]
 [45 55 65]]
[10 55]


In [50]:
a= np.array([1,2,3,4,5,6,7])
print(a[a>3])

print(a[a%2==0])

b1= np.array([2,3,4,5,6,7,8])

print(b1[1:5])
print(b1[:3])
print(b1[2:])

arr2d = np.arange(1,10).reshape(3,3)
print(arr2d)
print(arr2d[:2])
print(arr2d[:2,1:])   #row 0 and row 1 >> column 1, column 2
print(arr2d[1,:2])  #first two elements in second row(index 1)
print(arr2d[:2,2])
print(arr2d[:,:1])  #0th column , all rows


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[4 5]
[3 6]
[[1]
 [4]
 [7]]


In [53]:
names = np.array(['Bob', 'Joe', 'Tom', 'Bob', 'Tom', 'Joe', 'Joe'])
names

names =='Bob'

names[names=='Bob']


array(['Bob', 'Bob'], dtype='<U3')

In [74]:
arr=np.empty((8,4))

for i in range(8):
    arr[i]=i

arr

arr[[4,3,0,6]]

arr[[-3,-5]]

arr2 = np.arange(20) 
arrMask = (arr2%5 == 0)

arr2[arrMask]

arr2>10

arrMask2 = (arr2>=10)

arr2[arrMask2]

arr2[arrMask & arrMask2]

array([10, 15])

In [92]:
arr = np.arange(15).reshape((3,5))
arr

arr.transpose()

arr

arr.T

arr = np.random.randn(6,3)
arr

arr.T

np.dot(arr.T, arr)

arr_1 = np.arange(12).reshape(3,4)
print(arr_1)

arr_1.reshape(4,3)

arr_1.transpose(0,1)

arr_1.transpose(1,0)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [101]:
arr= np.arange(16).reshape((2,2,4))
print(arr)

# print(arr.transpose((1,0,2)))
# print(arr.transpose((0,1,2)))
#print(arr.transpose((2,1,0)))



help(arr.swapaxes)

arr.swapaxes(1,2)

arr.swapaxes(0,1)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
Help on built-in function swapaxes:

swapaxes(...) method of numpy.ndarray instance
    a.swapaxes(axis1, axis2)

    Return a view of the array with `axis1` and `axis2` interchanged.

    Refer to `numpy.swapaxes` for full documentation.

    See Also
    --------
    numpy.swapaxes : equivalent function



array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])