In [8]:
import pandas as pd
import numpy as np

def load_boston():
    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+",skiprows=22, header = None)
    data = np.hstack([raw_df.values[::2,:],raw_df.values[1::2,:2]])
    target = raw_df.values[1::2,2]
    return {'data':data, 'target':target}

boston = load_boston()
X = boston['data']
y = boston['target']
A = X[:4, [0,4,5,6]]
b = y[:4]

print("Solution:",np.linalg.solve(A,b))

Solution: [-3.12710043e+02 -1.15193942e+02  1.44996465e+01 -1.13259317e-01]


In [10]:
import pandas as pd
import numpy as np

def load_boston():
    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+",skiprows=22, header = None)
    data = np.hstack([raw_df.values[::2,:],raw_df.values[1::2,:2]])
    target = raw_df.values[1::2,2]
    return {'data':data, 'target':target}

boston = load_boston()
X = boston['data']
y = boston['target']
A = X[:4, [0,4,5,6]]
b = y[:4]

x_lstsq = np.linalg.lstsq(A, b, rcond=None)
print(x_lstsq)

(array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01]), array([], dtype=float64), np.int32(4), array([1.28391009e+02, 2.97333579e+00, 7.58898410e-02, 7.51932881e-03]))


In [31]:
import sympy as sp
x,y= sp.symbols('x y')
f = sp.exp((x**2)+(2*(y**2)))
fx= print("fx:",sp.diff(f, x))
fy = print("fy:",sp.diff(f,y))
fxx = print("fxx:",sp.diff(fx, x))
fxy = print("fxy:",sp.diff(fy, x))
fyx = print("fyx:",sp.diff(fx, y))
fyy = print("fyy:",sp.diff(fy, y))




fx: 2*x*exp(x**2 + 2*y**2)
fy: 4*y*exp(x**2 + 2*y**2)


TypeError: Cannot represent derivative of <class 'NoneType'>

In [32]:
import numpy as np

D = np.array([[2, 1 ],[1 ,2]])
eigenvalues , eigenvectors = np.linalg.eig(D)
print(eigenvalues)

[3. 1.]


In [33]:
import numpy as np
a = np.array([[2,0],[0,1]])
a_inv = np.linalg.inv(a)
print(a_inv)

[[0.5 0. ]
 [0.  1. ]]


In [35]:
import numpy as np
from sklearn.datasets import load_digits
X = load_digits().data
img1 = X[0]
img10 = X[9]

dot_sim = np.dot(img1, img10)
dot_similarity = np.dot(X, X.T)
print(dot_sim)
print(dot_similarity)

2807.0
[[3070. 1866. 2264. ... 2812. 3006. 2898.]
 [1866. 4209. 3432. ... 3906. 3083. 3307.]
 [2264. 3432. 4388. ... 4005. 3063. 3697.]
 ...
 [2812. 3906. 4005. ... 5092. 3729. 4598.]
 [3006. 3083. 3063. ... 3729. 4316. 3850.]
 [2898. 3307. 3697. ... 4598. 3850. 4938.]]
